<?php
namespace Modules\Hotel\Controllers;

use App\Http\Controllers\Controller;
use Modules\Hotel\Models\Hotel;
use Illuminate\Http\Request;
use Modules\Location\Models\Location;
use Modules\Review\Models\Review;
use Modules\Core\Models\Attributes;
use Illuminate\Pagination\LengthAwarePaginator as Paginator;
use DB;

class HotelController extends Controller
{
    protected $hotelClass;
    protected $locationClass;
    public function __construct()
    {
        $this->hotelClass = Hotel::class;
        $this->locationClass = Location::class;
    }
    public function callAction($method, $parameters)
    {
        if(!Hotel::isEnable())
        {
            return redirect('/');
        }
        return parent::callAction($method, $parameters); // TODO: Change the autogenerated stub
    }

    public function index(Request $request)
    {
        $is_ajax = $request->query('_ajax');
        $model_hotel = $this->hotelClass::select("bravo_hotels.*");
        $model_hotel->where("bravo_hotels.status", "publish");
        if (!empty($location_id = $request->query('location_id'))) {
            $location = $this->locationClass::where('id', $location_id)->where("status","publish")->first();
            if(!empty($location)){
                $model_hotel->join('bravo_locations', function ($join) use ($location) {
                    $join->on('bravo_locations.id', '=', 'bravo_hotels.location_id')
                        ->where('bravo_locations._lft', '>=', $location->_lft)
                        ->where('bravo_locations._rgt', '<=', $location->_rgt);
                });
            }
        }
        if (!empty($price_range = $request->query('price_range'))) {
            $pri_from = explode(";", $price_range)[0];
            $pri_to = explode(";", $price_range)[1];
            $raw_sql_min_max = "(  bravo_hotels.price >= ? ) 
                            AND (  bravo_hotels.price <= ? )";
            $model_hotel->WhereRaw($raw_sql_min_max,[$pri_from,$pri_to]);
        }

        if (!empty($star_rate = $request->query('star_rate'))) {
            $model_hotel->WhereIn('star_rate',$star_rate);
        }

        $terms = $request->query('terms');
        if($term_id = $request->query('term_id'))
        {
            $terms[] = $term_id;
        }
        if (is_array($terms) && !empty($terms)) {
            $model_hotel->join('bravo_hotel_term as tt', 'tt.target_id', "bravo_hotels.id")->whereIn('tt.term_id', $terms);
        }

        $model_hotel->orderBy("id", "desc");
        $model_hotel->groupBy("bravo_hotels.id");
        //$hotels_paginated = $model_hotel->with(['location','hasWishList','translations','termsByAttributeInListingPage'])->paginate(9);    
        $array_available_hotels = [];
        if ($request->query('start') && $request->query('end')) {
            $start_date = \Carbon\Carbon::createFromFormat('d/m/Y', $request->query('start'))->format('Y-m-d');
            $end_date = \Carbon\Carbon::createFromFormat('d/m/Y', $request->query('end'))->format('Y-m-d');
            $hotels = $model_hotel->with(['location','hasWishList','translations','termsByAttributeInListingPage'])->get();    
            foreach($hotels as $hotel) {
                /* if($hotel->isAvailableInRanges($start_date, $end_date) == 1) {
                    array_push($array_available_hotels, $hotel);
                } */
                $filters = [
                    'hotel_id' => $hotel->id,
                    'start_date' => $start_date,
                    'end_date' => $end_date
                ];
                if($hotel->getRoomsAvailability($filters)) {
                    array_push($array_available_hotels, $hotel);
                }
            }
            $count = count($array_available_hotels);
            $page = $request->page;
            $perPage = 9;
            $offset = ($page-1) * $perPage;
            $paginado = array_slice($array_available_hotels, $offset, $perPage);
            $list = new Paginator($paginado, $count, $perPage, $page, ['path'  => $request->url(),'query' => $request->query(),]);
            $list_for_map = collect($array_available_hotels);
        } else {
            $list = $model_hotel->with(['location','hasWishList','translations','termsByAttributeInListingPage'])->paginate(9);    
            $list_for_map = $model_hotel->with(['location','hasWishList','translations','termsByAttributeInListingPage'])->get();    
        } 
        

        

        $markers = [];
        if (!empty($list_for_map)) {
            foreach ($list_for_map as $row) {
                $markers[] = [
                    "id"      => $row->id,
                    "title"   => $row->title,
                    "lat"     => (float)$row->map_lat,
                    "lng"     => (float)$row->map_lng,
                    "gallery" => $row->getGallery(true),
                    "infobox" => view('Hotel::frontend.layouts.search.loop-list-map', ['row' => $row,'disable_lazyload'=>1,'wrap_class'=>'infobox-item'])->render(),
                    'marker'  => url('images/icons/png/esq_red.png'),
                    'price'   => $row->price
                ];
            }
        }
        $limit_location = 15;
        if( empty(setting_item("hotel_location_search_style")) or setting_item("hotel_location_search_style") == "normal" ){
            $limit_location = 1000;
        }
        
        $data = [
            'rows'               => $list,
            'list_location'      => $this->locationClass::where('status', 'publish')->limit($limit_location)->with(['translations'])->get()->toTree(),
            'hotel_min_max_price' => $this->hotelClass::getMinMaxPrice(),
            'markers'            => $markers,
            "blank"              => 1,
            "seo_meta"           => $this->hotelClass::getSeoMetaForPageList(),
            
        ];
        $layout = setting_item("hotel_layout_search", 'normal');
        if ($request->query('_layout')) {
            $layout = $request->query('_layout');
        }
        if ($is_ajax) {
            $this->sendSuccess([
                'html'    => view('Hotel::frontend.layouts.search-map.list-item', $data)->render(),
                "markers" => $data['markers'],
                'location_lat' => $location->map_lat,
                'location_lng' => $location->map_lng, 
            ]);
        }
        $data['attributes'] = Attributes::where('service', 'hotel')->with(['terms','translations'])->get();

        if ($layout == "map") {
            $data['body_class'] = 'has-search-map';
            $data['html_class'] = 'full-page';
            return view('Hotel::frontend.search-map', $data);
        }
        return view('Hotel::frontend.search', $data);
    }

    public function detail(Request $request, $slug)
    {
        $row = $this->hotelClass::where('slug', $slug)->where("status", "publish")->with(['location','translations','hasWishList', 'termsByAttributeInListingPage'])->first();;
        if (empty($row)) {
            return redirect('/');
        }
        $translation = $row->translateOrOrigin(app()->getLocale());
        $hotel_related = [];
        $location_id = $row->location_id;
        if (!empty($location_id)) {
            $hotel_related = $this->hotelClass::where('location_id', $location_id)->where("status", "publish")->take(4)->whereNotIn('id', [$row->id])->with(['location','translations','hasWishList'])->get();
        }
        $review_list = Review::where('object_id', $row->id)->where('object_model', 'hotel')->where("status", "approved")->orderBy("id", "desc")->with('author')->paginate(setting_item('hotel_review_number_per_page', 5));
        $data = [
            'row'          => $row,
            'translation'  => $translation,
            'hotel_related' => $hotel_related,
            'booking_data' => $row->getBookingData(),
            'review_list'  => $review_list,
            'seo_meta'  => $row->getSeoMetaWithTranslation(app()->getLocale(),$translation),
            'body_class'=>'is_single'
        ];
        $this->setActiveMenu($row);
        return view('Hotel::frontend.detail', $data)->with('data', $data);
    }

    public function checkAvailability(){
        $hotel_id = \request('hotel_id');

        if(!\request()->input('firstLoad')) {
            request()->validate([
                'hotel_id'   => 'required',
                'start_date' => 'required:date_format:Y-m-d',
                'end_date'   => 'required:date_format:Y-m-d',
                'adults'     => 'required',
            ]);

            if(strtotime(\request('end_date')) - strtotime(\request('start_date')) < DAY_IN_SECONDS){
                $this->sendError(__("Dates are not valid"));
            }
            if(strtotime(\request('end_date')) - strtotime(\request('start_date')) > 30*DAY_IN_SECONDS){
                $this->sendError(__("Maximum day for booking is 30"));
            }
        }

        $hotel = $this->hotelClass::find($hotel_id);
        if(empty($hotel_id) or empty($hotel)){
            $this->sendError(__("Hotel not found"));
        }

        $rooms = $hotel->getRoomsAvailability(request()->input());

        $this->sendSuccess([
            'rooms'=>$rooms
        ]);
    }

    
}
